export enum ConfigKeys {
  ADMIN_EMAIL = 'ADMIN_EMAIL',
  CLUSTER_NAME = 'CLUSTER_NAME',
  HOSTED_ZONE_NAME = 'HOSTED_ZONE_NAME',
  GITHUB_HOST = 'GITHUB_HOST',
  GITHUB_OWNER = 'GITHUB_OWNER',
  ARGO_WORKFLOWS_URL = "ARGO_WORKFLOWS_URL",
  VAULT_URL = "VAULT_URL",
  ARGO_CD_URL = "ARGO_CD_URL",
  MINIO_URL = "MINIO_URL",
  MINIO_CONOSLE_URL = "MINIO_CONOSLE_URL",
}
