export enum Services {
  ATLANTIS = 'ATLANTIS',
  ARGO = 'ARGO',
  ARGOCD = 'ARGOCD',
  GITHUB = 'GITHUB',
  GITLAB = 'GITLAB',
  METAPHOR = 'METAPHOR',
  METAPHOR_STG = 'METAPHOR_STAGING',
  METAPHOR_PRODUCTION = 'METAPHOR_PRODUCTION',
  VAULT = 'VAULT',
}
