import type { NextApiRequest, NextApiResponse } from 'next';

type Configs = {
  [key: string]: string;
};

export default function handler(req: NextApiRequest, res: NextApiResponse<Configs>) {
  const {
    HOSTED_ZONE_NAME = '',
    ADMIN_EMAIL = '',
    CLUSTER_NAME = '',
    GITHUB_HOST = '',
    GITHUB_OWNER = '',
    ARGO_WORKFLOWS_URL = '',
    VAULT_URL = '',
    ARGO_CD_URL = '',
    ATLANTIS_URL = '',
    METAPHOR_DEV = '',
    METAPHOR_GO_DEV = '',
    METAPHOR_FRONT_DEV = '',
    METAPHOR_STAGING = '',
    METAPHOR_GO_STAGING = '',
    METAPHOR_FRONT_STAGING = '',
    METAPHOR_PROD = '',
    METAPHOR_GO_PROD = '',
    METAPHOR_FRONT_PROD = '',
    KUBEFIRST_VERSION = '',
    NEW_ENV_VAR = '',
  } = process.env;

  res.status(200).json({
    HOSTED_ZONE_NAME: HOSTED_ZONE_NAME,
    ADMIN_EMAIL: ADMIN_EMAIL,
    CLUSTER_NAME: CLUSTER_NAME,
    GITHUB_HOST: GITHUB_HOST,
    GITHUB_OWNER: GITHUB_OWNER,
    ARGO_WORKFLOWS_URL: ARGO_WORKFLOWS_URL,
    VAULT_URL: VAULT_URL,
    ARGO_CD_URL: ARGO_CD_URL,
    ATLANTIS_URL: ATLANTIS_URL,
    METAPHOR_DEV: METAPHOR_DEV,
    METAPHOR_GO_DEV: METAPHOR_GO_DEV,
    METAPHOR_FRONT_DEV: METAPHOR_FRONT_DEV,
    METAPHOR_STAGING: METAPHOR_STAGING,
    METAPHOR_GO_STAGING: METAPHOR_GO_STAGING,
    METAPHOR_FRONT_STAGING: METAPHOR_FRONT_STAGING,
    METAPHOR_PROD: METAPHOR_PROD,
    METAPHOR_GO_PROD: METAPHOR_GO_PROD,
    METAPHOR_FRONT_PROD: METAPHOR_FRONT_PROD,
    KUBEFIRST_VERSION: KUBEFIRST_VERSION,
    NEW_ENV_VAR: NEW_ENV_VAR,
  });
}
