import { DefaultTheme } from '@/app/lib/styled-components';
import {
  AMERICAN_BLUE,
  AMERICAN_GREEN,
  ATHENA_BLUE,
  BELUGA,
  BLACK,
  BLEACHED_SILK,
  CARIBEAN_SEA,
  CHILD_OF_LIGHT,
  CHINESE_ORANGE,
  DANGER,
  DAWN_DEPARTS,
  FERNTASTIC,
  GRAVE_FLINT,
  GRAY,
  GREEN_JELLY,
  JORDY_BLUE,
  MOONLESS_MYTERY,
  NAIVE_PEACH,
  PRIMARY,
  PURPLE_CABBAGE,
  SALTBOX_BLUE,
  STORMY_SHOWER,
  TRANSPARENT_BLUE,
  ULTIMATE_GREY,
  YELLOW_ORANGE,
  VOLCANIC_SAND,
  WASH_ME,
  WHITE,
  WHITE_SMOKE,
  LIGHT_GREY,
  SPUN_PEARL,
  LIBERTY_BLUE,
  FIRE_BRICK,
  MAGNOLIA,
  ROYAL_PURPLE,
  SEFID_WHITE,
  PASTEL_LIGHT_BLUE,
  METRO,
  EXCLUSIVE_PLUM,
} from '@/constants/colors';

export const theme: DefaultTheme = {
  colors: {
    americanBlue: AMERICAN_BLUE,
    americanGreen: AMERICAN_GREEN,
    athenaBlue: ATHENA_BLUE,
    beluga: BELUGA,
    black: BLACK,
    bleachedSilk: BLEACHED_SILK,
    caribeanSea: CARIBEAN_SEA,
    childOfLight: CHILD_OF_LIGHT,
    chineseOrange: CHINESE_ORANGE,
    danger: DANGER,
    dawnDeparts: DAWN_DEPARTS,
    ferntastic: FERNTASTIC,
    gravelFint: GRAVE_FLINT,
    gray: GRAY,
    greenJelly: GREEN_JELLY,
    jordyBlue: JORDY_BLUE,
    moonlessMystery: MOONLESS_MYTERY,
    naivePeach: NAIVE_PEACH,
    primary: PRIMARY,
    purpleCabbage: PURPLE_CABBAGE,
    saltboxBlue: SALTBOX_BLUE,
    stomyShower: STORMY_SHOWER,
    spunPearl: SPUN_PEARL,
    transparentBlue: TRANSPARENT_BLUE,
    ultimateGrey: ULTIMATE_GREY,
    yellowOrange: YELLOW_ORANGE,
    volcanicSand: VOLCANIC_SAND,
    washMe: WASH_ME,
    white: WHITE,
    whiteSmoke: WHITE_SMOKE,
    lightGrey: LIGHT_GREY,
    libertyBlue: LIBERTY_BLUE,
    fireBrick: FIRE_BRICK,
    magnolia: MAGNOLIA,
    royanPurple: ROYAL_PURPLE,
    sefidWhite: SEFID_WHITE,
    pastelLightBlue: PASTEL_LIGHT_BLUE,
    metro: METRO,
    exclusivePlum: EXCLUSIVE_PLUM,
  },
};
